apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopkart
  labels:
    app: shopkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopkart
  template:
    metadata:
      labels:
        app: shopkart
    spec:
      containers:
        - name: shopkart
          image: 382755779648.dkr.ecr.us-east-1.amazonaws.com/shopkart-repo:a0fe322718d1634bbd4832bf0afdf710605fade4
          ports:
            - containerPort: 3000

          envFrom:
            - secretRef:
                name: shopkart-db-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
