name: ShopKart - Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: shopkart-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show GitHub repository identity
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository ID: ${{ github.event.repository.id }}"
          echo "Owner: ${{ github.repository_owner }}"
          echo "Owner ID: ${{ github.event.repository.owner.id }}"
          echo "Ref: ${{ github.ref }}"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::382755779648:role/Shopkart-GitHub-Actions-Role
          role-session-name: ShopKartGitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: 382755779648.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}-${{ github.run_attempt }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -f ./application/Dockerfile \
            ./application

      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: 382755779648.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}-${{ github.run_attempt }}
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name shopkart-eks \
            --region ${{ env.AWS_REGION }}

      - name: Verify EKS access
        run: |
          kubectl auth can-i get deployments
          kubectl auth can-i patch deployments
          kubectl get deployment shopkart

      - name: Deploy image to EKS
        env:
          ECR_REGISTRY: 382755779648.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/shopkart \
            shopkart=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Verify deployment rollout
        run: |
          kubectl rollout status deployment/shopkart --timeout=180s